#!/usr/bin/env python3
import bcrypt
from datetime import datetime
import pytz

from app import db, User, QueuedPaper, ReadPaper

db.create_all()
timestamp = datetime.now(pytz.timezone('America/Los_Angeles'))

# Add user first to create the user ID
u1 = User(
        username='user',
        password_hash = bcrypt.hashpw('testpassword'.encode(), bcrypt.gensalt()))
db.session.add(u1)
db.session.commit()

# Now add papers
q1 = QueuedPaper(
        user_id = u1.id,
        authors='Alice', 
        title='Towards Being Alice', 
        venue='ICML', 
        year=1994, 
        priority=0,
        url='https://icons.getbootstrap.com/icons/book/')
r1 = ReadPaper(
        user_id = u1.id,
        authors='Bob',
        title='Bobology',
        venue='ACL',
        year=2004,
        date_added=timestamp,
        status=2,
        url='https://icons.getbootstrap.com/icons/link/',
        note='This is about Bobology.')
db.session.add(q1)
db.session.add(r1)
db.session.commit()
